version: "local" 
train_path: "data/race/high/train-00000-of-00001.parquet"
test_path: "data/race/high/test-00000-of-00001.parquet"
template: ${infer_model.prompt_templates.race_prompt_template}  # 引用infer_model中定义的RACE_HIGH prompt模板 
name: "race_high"